# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Alumnos', '0003_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(choices=[('Sotfware', 'Sotfware'), ('Hardware', 'Hardware')], max_length=10)),
                ('estado', models.CharField(max_length=30)),
                ('prioridad', models.CharField(max_length=30)),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Alumnos.Alumno')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Alumnos.Equipo')),
            ],
        ),
    ]
