# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[(1, 'Abierta'), ('Cerrada', 'Cerrada'), ('Retrasada', 'Retrasada'), ('Fijada', 'Fijada')], max_length=20),
        ),
    ]
