# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0003_auto_20180424_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[(1, 'Abierta'), (2, 'Cerrada'), (3, 'Retrasada'), (4, 'Fijada')], max_length=20),
        ),
    ]
