# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0004_auto_20180424_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[(1, 'Normal'), (2, 'Alta'), (3, 'Muy alta')], max_length=30),
        ),
    ]
