# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0005_auto_20180424_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(default='Descripcion', max_length=250),
            preserve_default=False,
        ),
    ]
