# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-06 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0006_solicitud_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Incidencia', 'Incidencia'), ('Peticion', 'Peticion'), ('Problema', 'Problema')], default='Incidencia', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Retrasada', 'Retrasada'), ('Fijada', 'Fijada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alta', 'Alta'), ('Muy alta', 'Muy alta')], max_length=30),
        ),
    ]
