# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0007_alumno_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion_Solicitudes', '0007_auto_20180506_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('resolucion', models.DateTimeField()),
                ('solucion', models.TextField(max_length=250)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Alumnos.Alumno')),
                ('usuarioAsignado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
