# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0008_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
