# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0011_auto_20180526_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
