# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Solicitudes', '0013_auto_20180530_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
