# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0011_auto_20180527_1331'),
        ('Gestion_Solicitudes', '0015_auto_20180603_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='usuario',
        ),
        migrations.AddField(
            model_name='actividad',
            name='alumno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Alumnos.Alumno'),
        ),
    ]
