# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='timestamp',
            new_name='registro',
        ),
    ]
