# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0003_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
