# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0006_alumno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
