# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0007_alumno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Alumnos.Equipo'),
        ),
    ]
