# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0008_auto_20180526_1837'),
        ('Gestion_Alumnos', '0008_auto_20180525_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Alumnos.Alumno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Centros.Curso')),
            ],
        ),
    ]
