# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0009_asignatura_asignaturacurso'),
        ('Gestion_Alumnos', '0009_cursoalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Centros.Curso'),
        ),
    ]
