# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Alumnos', '0010_alumno_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoalumno',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='cursoalumno',
            name='curso',
        ),
        migrations.DeleteModel(
            name='CursoAlumno',
        ),
    ]
