# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Profesores', '0002_profesorcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorcurso',
            name='descripcion',
            field=models.TextField(default='Curso para aprender algo xD', max_length=30),
            preserve_default=False,
        ),
    ]
