# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('localidad', models.CharField(max_length=50)),
                ('cp', models.IntegerField()),
                ('provincia', models.CharField(max_length=40)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
