# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0002_auto_20180420_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('letra', models.CharField(blank=True, max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
