# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0005_cursoalumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoalumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='cursoalumno',
            name='curso',
            field=models.ManyToManyField(to='Gestion_Centros.Curso'),
        ),
        migrations.RemoveField(
            model_name='cursoaula',
            name='aula',
        ),
        migrations.AddField(
            model_name='cursoaula',
            name='aula',
            field=models.ManyToManyField(to='Gestion_Centros.Aula'),
        ),
        migrations.RemoveField(
            model_name='cursoaula',
            name='curso',
        ),
        migrations.AddField(
            model_name='cursoaula',
            name='curso',
            field=models.ManyToManyField(to='Gestion_Centros.Curso'),
        ),
    ]
