# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0006_auto_20180526_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoalumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='cursoalumno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Centros.Curso'),
        ),
        migrations.RemoveField(
            model_name='cursoaula',
            name='aula',
        ),
        migrations.AddField(
            model_name='cursoaula',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Centros.Aula'),
        ),
        migrations.RemoveField(
            model_name='cursoaula',
            name='curso',
        ),
        migrations.AddField(
            model_name='cursoaula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Centros.Curso'),
        ),
    ]
