# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0007_auto_20180526_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoalumno',
            name='curso',
        ),
        migrations.DeleteModel(
            name='CursoAlumno',
        ),
    ]
