# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0013_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='nombreFichero',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
