# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0015_tema_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(default='Descripcion asignatura ....', max_length=30),
            preserve_default=False,
        ),
    ]
