# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0016_asignatura_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='curso',
        ),
    ]
