# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Centros', '0017_remove_aula_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='incidencia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
